# GitHub Enterprise Documentation:
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
#
name: Create Repo
description: Request creation of GitHub repository
title: "[Create Repo]: "
labels:
  - administration
  - create_repo
body:
  - type: markdown
    attributes:
      value: |
        Need repository created?

        Fill out this form, get a `/lgtm` comment, and you're golden!
  - type: input
    id: repository-name
    attributes:
      label: Repository name
      description: Great repository names are short and memorable.
    validations:
      required: true
  - type: input
    id: repository-description
    attributes:
      label: Repository description
  - type: input
    id: tool-name
    attributes:
      label: Tool Name
  - type: dropdown
    id: product-name
    attributes:
      label: Product Name
      # description: |
      #   - **Public**: Anyone on the internet can see this repository. You choose who can commit.
      #   - **Internal**: Enterprise members can see this repository. You choose who can commit.
      #   - **Private**: You choose who can see and commit to this repository.
      options:
        - SCM
        - CRM-PRM
        - PMT
    validations:
      required: true
  - type: checkboxes
    id: workflow-name
    attributes:
      label: What kinds of workflows would you like to have?
      description: You may select more than one.
      options:
        - label: ALM Intgration
        - label: Doc-as-code workflows
        - label: CX workflows
        
  
  
       
